namespace NASCAR_Money.Models
{
    public class LiveOps
    {
        public string live_series_1_logo { get; set; }
        public string live_series_2_logo { get; set; }
        public string live_series_3_logo { get; set; }
        public string live_series_4_logo { get; set; }
        public string weather_lat { get; set; }
        public string weather_long { get; set; }
        public string live_splash_screen { get; set; }
        public string live_current_year { get; set; }
        public string live_pre_current_year { get; set; }
        public string live_series_1 { get; set; }
        public string live_series_2 { get; set; }
        public string live_series_3 { get; set; }
        public string live_series_4 { get; set; }
        public string trending_nav_label { get; set; }
        public string trending_nav_mode { get; set; }
        public string trending_nav_live_feed_url { get; set; }
        public string trending_nav_rc_cta_url { get; set; }
        public string trending_nav_results_cta_url { get; set; }
        public string live_stream_tracking_txt { get; set; }
        public string quick_links_series { get; set; }
        public string live_scanner_feed_url { get; set; }
        public string live_scanner_feed_url_2 { get; set; }
        public string live_scanner_feed_url_3 { get; set; }
        public string live_video_feed_url { get; set; }
        public string live_redirect_url { get; set; }
        public string live_video_page_redirect_url { get; set; }
        public string live_feed_refresh_interval { get; set; }
        public string rc_icon_feed { get; set; }
        public string live_trophy_chase { get; set; }
        public string live_trophy_white_chase { get; set; }
        public string live_graphical_indicators_stage1indicatorLabel { get; set; }
        public string live_graphical_indicators_stage1indicatorColor { get; set; }
        public string live_graphical_indicators_stage1indicatorText { get; set; }
        public string live_graphical_indicators_stage2indicatorLabel { get; set; }
        public string live_graphical_indicators_stage2indicatorColor { get; set; }
        public string live_graphical_indicators_stage2indicatorText { get; set; }
        public string live_graphical_indicators_stage3indicatorLabel { get; set; }
        public string live_graphical_indicators_stage3indicatorColor { get; set; }
        public string live_graphical_indicators_stage3indicatorText { get; set; }
        public string live_graphical_indicators_rookieIndicatorLabel { get; set; }
        public string live_graphical_indicators_rookieIndicatorColor { get; set; }
        public string live_graphical_indicators_rookieIndicatorText { get; set; }
        public string live_graphical_indicators_ineligibleIndicatorLabel { get; set; }
        public string live_graphical_indicators_ineligibleIndicatorColor { get; set; }
        public string live_graphical_indicators_ineligibleIndicatorText { get; set; }
        public string live_graphical_indicators_playoffsIndicatorLabel { get; set; }
        public string live_graphical_indicators_playoffsIndicatorColor { get; set; }
        public string live_graphical_indicators_playoffsIndicatorText { get; set; }
        public string live_graphical_indicators_clinchIndicatorLabel { get; set; }
        public string live_graphical_indicators_clinchIndicatorColor { get; set; }
        public string live_graphical_indicators_clinchIndicatorText { get; set; }
        public string live_graphical_indicators_seasonIndicatorLabel { get; set; }
        public string live_graphical_indicators_seasonIndicatorColor { get; set; }
        public string live_graphical_indicators_seasonIndicatorText { get; set; }
        public string live_indicator_enabled_pages { get; set; }
        public string chase_current_round1 { get; set; }
        public string chase_round_of1 { get; set; }
        public string cut_off_line1 { get; set; }
        public string live_feed_url_series1 { get; set; }
        public string live_points_feed_url_series1 { get; set; }
        public string live_drive_leaderboard_url_series1 { get; set; }
        public string live_drive_draftkings_url_series1 { get; set; }
        public string driver_points_feed_url_series1 { get; set; }
        public string owner_points_feed_url_series1 { get; set; }
        public string live_drive_laps_stage1_series1 { get; set; }
        public string live_drive_laps_stage2_series1 { get; set; }
        public string live_drive_laps_stage3_series1 { get; set; }
        public string live_rc_schedule_widget_mode_series1 { get; set; }
        public string hero_live_player_cta_url_series1 { get; set; }
        public string hero_live_player_stream_series1 { get; set; }
        public string hero_post_player_title_series1 { get; set; }
        public string hero_post_player_url_series1 { get; set; }
        public string hero_post_player_stream_series1 { get; set; }
        public string hero_post_player_button1_text_series1 { get; set; }
        public string hero_post_player_button1_url_series1 { get; set; }
        public string hero_post_player_button2_text_series1 { get; set; }
        public string hero_post_player_button2_url_series1 { get; set; }
        public string hero_live_scanner_title_series1 { get; set; }
        public string hero_live_scanner_stream_series1 { get; set; }
        public string live_current_series1_race { get; set; }
        public string live_current_series1_radio_feed_url { get; set; }
        public string live_current_series1_raceview_race { get; set; }
        public string live_current_series1_scanner_race { get; set; }
        public string series1_live_mobile_camera_title_1 { get; set; }
        public string series1_live_mobile_camera_driver_id_1 { get; set; }
        public string series1_live_mobile_camera_url_1 { get; set; }
        public string series1_live_mobile_camera_ssid_1 { get; set; }
        public string series1_live_mobile_camera_description_1 { get; set; }
        public string series1_live_mobile_camera_thumbnail_1 { get; set; }
        public string series1_live_mobile_camera_fallback_1 { get; set; }
        public string series1_live_mobile_camera_count { get; set; }
        public string chase_current_round2 { get; set; }
        public string chase_round_of2 { get; set; }
        public string cut_off_line2 { get; set; }
        public string live_feed_url_series2 { get; set; }
        public string live_points_feed_url_series2 { get; set; }
        public string live_drive_leaderboard_url_series2 { get; set; }
        public string live_drive_draftkings_url_series2 { get; set; }
        public string driver_points_feed_url_series2 { get; set; }
        public string owner_points_feed_url_series2 { get; set; }
        public string live_drive_laps_stage1_series2 { get; set; }
        public string live_drive_laps_stage2_series2 { get; set; }
        public string live_drive_laps_stage3_series2 { get; set; }
        public string live_rc_schedule_widget_mode_series2 { get; set; }
        public string hero_live_player_cta_url_series2 { get; set; }
        public string hero_live_player_stream_series2 { get; set; }
        public string hero_post_player_title_series2 { get; set; }
        public string hero_post_player_url_series2 { get; set; }
        public string hero_post_player_stream_series2 { get; set; }
        public string hero_post_player_button1_text_series2 { get; set; }
        public string hero_post_player_button1_url_series2 { get; set; }
        public string hero_post_player_button2_text_series2 { get; set; }
        public string hero_post_player_button2_url_series2 { get; set; }
        public string hero_live_scanner_title_series2 { get; set; }
        public string hero_live_scanner_stream_series2 { get; set; }
        public string live_current_series2_race { get; set; }
        public string live_current_series2_radio_feed_url { get; set; }
        public string live_current_series2_raceview_race { get; set; }
        public string live_current_series2_scanner_race { get; set; }
        public string series2_live_mobile_camera_title_1 { get; set; }
        public string series2_live_mobile_camera_driver_id_1 { get; set; }
        public string series2_live_mobile_camera_url_1 { get; set; }
        public string series2_live_mobile_camera_ssid_1 { get; set; }
        public string series2_live_mobile_camera_description_1 { get; set; }
        public string series2_live_mobile_camera_thumbnail_1 { get; set; }
        public string series2_live_mobile_camera_fallback_1 { get; set; }
        public string series2_live_mobile_camera_count { get; set; }
        public string chase_current_round3 { get; set; }
        public string chase_round_of3 { get; set; }
        public string cut_off_line3 { get; set; }
        public string live_feed_url_series3 { get; set; }
        public string live_points_feed_url_series3 { get; set; }
        public string live_drive_leaderboard_url_series3 { get; set; }
        public string live_drive_draftkings_url_series3 { get; set; }
        public string driver_points_feed_url_series3 { get; set; }
        public string owner_points_feed_url_series3 { get; set; }
        public string live_drive_laps_stage1_series3 { get; set; }
        public string live_drive_laps_stage2_series3 { get; set; }
        public string live_drive_laps_stage3_series3 { get; set; }
        public string live_rc_schedule_widget_mode_series3 { get; set; }
        public string hero_live_player_cta_url_series3 { get; set; }
        public string hero_live_player_stream_series3 { get; set; }
        public string hero_post_player_title_series3 { get; set; }
        public string hero_post_player_url_series3 { get; set; }
        public string hero_post_player_stream_series3 { get; set; }
        public string hero_post_player_button1_text_series3 { get; set; }
        public string hero_post_player_button1_url_series3 { get; set; }
        public string hero_post_player_button2_text_series3 { get; set; }
        public string hero_post_player_button2_url_series3 { get; set; }
        public string hero_live_scanner_title_series3 { get; set; }
        public string hero_live_scanner_stream_series3 { get; set; }
        public string live_current_series3_race { get; set; }
        public string live_current_series3_radio_feed_url { get; set; }
        public string live_current_series3_raceview_race { get; set; }
        public string live_current_series3_scanner_race { get; set; }
        public string series3_live_mobile_camera_title_1 { get; set; }
        public string series3_live_mobile_camera_driver_id_1 { get; set; }
        public string series3_live_mobile_camera_url_1 { get; set; }
        public string series3_live_mobile_camera_ssid_1 { get; set; }
        public string series3_live_mobile_camera_description_1 { get; set; }
        public string series3_live_mobile_camera_thumbnail_1 { get; set; }
        public string series3_live_mobile_camera_fallback_1 { get; set; }
        public string series3_live_mobile_camera_count { get; set; }
        public string livestream_live_mobile_camera_title_1 { get; set; }
        public string livestream_live_mobile_camera_driver_id_1 { get; set; }
        public string livestream_live_mobile_camera_url_1 { get; set; }
        public string livestream_live_mobile_camera_ssid_1 { get; set; }
        public string livestream_live_mobile_camera_description_1 { get; set; }
        public string livestream_live_mobile_camera_thumbnail_1 { get; set; }
        public string livestream_live_mobile_camera_fallback_1 { get; set; }
        public string livestream_live_mobile_camera_count { get; set; }
        public string drive_betting_odds { get; set; }
        public string live_drive_series { get; set; }
        public string live_drive_heartbeat_interval { get; set; }
        public string live_drive_leaderboard_enabled { get; set; }
        public string live_drive_leaderboard_visible { get; set; }
        public string live_drive_draftkings_enabled { get; set; }
        public string live_drive_draftkings_visible { get; set; }
        public string draftkings_draftables_url { get; set; }
        public string draftkings_draftpool_url { get; set; }
        public string draftkings_logo_url { get; set; }
        public string live_drive_live_on_image { get; set; }
        public string live_drive_default_desktop_camera { get; set; }
        public string live_drive_default_mobile_camera { get; set; }
        public string live_drive_series_mobile_camera { get; set; }
        public string live_mobile_series { get; set; }
        public string live_mobile_run_type { get; set; }
        public string live_mobile_series_post_1 { get; set; }
        public string live_mobile_series_post_2 { get; set; }
        public string live_mobile_series_post_3 { get; set; }
        public string live_alert_desc { get; set; }
        public string live_fanrewards_code { get; set; }
        public string live_fanrewards_join { get; set; }
        public string live_fanrewards_points_collect { get; set; }
        public string live_fanrewards_points_collected { get; set; }
        public string live_mobile_current_series1_race { get; set; }
        public string live_mobile_next_series1_race { get; set; }
        public string live_camera_mobile_series1_check { get; set; }
        public string live_camera_mobile_series1_title { get; set; }
        public string live_camera_mobile_series1_desc { get; set; }
        public string live_audio_mobile_series1_check { get; set; }
        public string live_audio_mobile_series1_title { get; set; }
        public string live_audio_mobile_series1_desc { get; set; }
        public string live_dot_mobile_series1_check { get; set; }
        public string live_dot_mobile_series1_title { get; set; }
        public string live_dot_mobile_series1_desc { get; set; }
        public string live_highlight_mobile_series1_check { get; set; }
        public string live_highlight_mobile_series1_title { get; set; }
        public string live_highlight_mobile_series1_desc { get; set; }
        public string live_driver_comparison_mobile_series1_check { get; set; }
        public string live_driver_comparison_mobile_series1_title { get; set; }
        public string live_driver_comparison_mobile_series1_desc { get; set; }
        public string live_timeline_mobile_series1_check { get; set; }
        public string live_timeline_mobile_series1_title { get; set; }
        public string live_timeline_mobile_series1_desc { get; set; }
        public string live_mobile_current_series2_race { get; set; }
        public string live_mobile_next_series2_race { get; set; }
        public string live_camera_mobile_series2_check { get; set; }
        public string live_camera_mobile_series2_title { get; set; }
        public string live_camera_mobile_series2_desc { get; set; }
        public string live_audio_mobile_series2_check { get; set; }
        public string live_audio_mobile_series2_title { get; set; }
        public string live_audio_mobile_series2_desc { get; set; }
        public string live_dot_mobile_series2_check { get; set; }
        public string live_dot_mobile_series2_title { get; set; }
        public string live_dot_mobile_series2_desc { get; set; }
        public string live_highlight_mobile_series2_check { get; set; }
        public string live_highlight_mobile_series2_title { get; set; }
        public string live_highlight_mobile_series2_desc { get; set; }
        public string live_driver_comparison_mobile_series2_check { get; set; }
        public string live_driver_comparison_mobile_series2_title { get; set; }
        public string live_driver_comparison_mobile_series2_desc { get; set; }
        public string live_timeline_mobile_series2_check { get; set; }
        public string live_timeline_mobile_series2_title { get; set; }
        public string live_timeline_mobile_series2_desc { get; set; }
        public string live_mobile_current_series3_race { get; set; }
        public string live_mobile_next_series3_race { get; set; }
        public string live_camera_mobile_series3_check { get; set; }
        public string live_camera_mobile_series3_title { get; set; }
        public string live_camera_mobile_series3_desc { get; set; }
        public string live_audio_mobile_series3_check { get; set; }
        public string live_audio_mobile_series3_title { get; set; }
        public string live_audio_mobile_series3_desc { get; set; }
        public string live_dot_mobile_series3_check { get; set; }
        public string live_dot_mobile_series3_title { get; set; }
        public string live_dot_mobile_series3_desc { get; set; }
        public string live_highlight_mobile_series3_check { get; set; }
        public string live_highlight_mobile_series3_title { get; set; }
        public string live_highlight_mobile_series3_desc { get; set; }
        public string live_driver_comparison_mobile_series3_check { get; set; }
        public string live_driver_comparison_mobile_series3_title { get; set; }
        public string live_driver_comparison_mobile_series3_desc { get; set; }
        public string live_timeline_mobile_series3_check { get; set; }
        public string live_timeline_mobile_series3_title { get; set; }
        public string live_timeline_mobile_series3_desc { get; set; }
        public string live_racecenter_settings_hide_telemetry { get; set; }
        public string live_racecenter_settings_rw_logo { get; set; }
        public string live_racecenter_settings_rw_mobile_logo { get; set; }
        public string live_racecenter_settings_rw_learn_more_btn_URL { get; set; }
        public string live_racecenter_settings_rw_jn_cpy_lb_clpsed { get; set; }
        public string live_racecenter_settings_rw_jn_cpy_lb_expd { get; set; }
        public string live_racecenter_settings_rw_ckn_cta_txt { get; set; }
        public string live_racecenter_settings_rw_ckn_cta_txt_lb_expnd { get; set; }
        public string live_racecenter_settings_rw_ckn_cd { get; set; }
        public string live_racecenter_settings_rw_chckn_cpy_lb_clpsed { get; set; }
        public string live_racecenter_settings_rw_chckn_cpy_lb_expd { get; set; }
        public string live_racecenter_settings_rw_chckn_pts_lb_clpsed { get; set; }
        public string live_racecenter_settings_rw_chckd_cpy_lb_clpsed { get; set; }
        public string live_racecenter_settings_rw_chckd_cpy_lb_expd { get; set; }
        public string live_racecenter_settings_rw_chckd_pts_lb_clpsed { get; set; }
        public string live_racecenter_settings_rw_mbl_cpy_jn { get; set; }
        public string live_racecenter_settings_rw_mbl_cpy_chcknd { get; set; }
        public string live_racecenter_settings_rw_mbl_cpy_chckn { get; set; }
        public string live_racecenter_settings_scanner_button_name { get; set; }
        public string live_racecenter_settings_scanner_button_cta { get; set; }
        public string live_racecenter_settings_scanner_cta_text { get; set; }
        public string live_racecenter_settings_scanner_popup_mp1_btn_cta { get; set; }
        public string live_racecenter_settings_scanner_popup_mp1_btn_nm { get; set; }
        public string live_racecenter_settings_scanner_popup_mp2_btn_cta { get; set; }
        public string live_racecenter_settings_scanner_popup_mp2_btn_nm { get; set; }
        public string live_racecenter_settings_scanner_popup_lginbtnCpy { get; set; }
        public string live_racecenter_settings_scanner_popup_lgin_btn_nm { get; set; }
        public string live_racecenter_settings_scanner_popup_Logo { get; set; }
        public string live_racecenter_settings_scanner_popup_scannerText { get; set; }
        public string live_racecenter_settings_scanner_ads_id { get; set; }
        public string live_racecenter_settings1_race_id { get; set; }
        public string live_racecenter_settings1_live_feed_url { get; set; }
        public string live_racecenter_settings1_live_standings_url { get; set; }
        public string live_racecenter_settings1_live_stage_points_url { get; set; }
        public string live_racecenter_settings1_weekend_feed_url { get; set; }
        public string live_racecenter_settings1_points_url { get; set; }
        public string live_racecenter_settings1_snappytv_feed_url { get; set; }
        public string live_racecenter_settings1_lap_notes_url { get; set; }
        public string live_racecenter_settings1_lap_times_url { get; set; }
        public string live_racecenter_settings1_driver_recap_url { get; set; }
        public string live_racecenter_settings1_lap_averages_url { get; set; }
        public string live_racecenter_settings1_live_flag_data_url { get; set; }
        public string live_racecenter_settings1_pit_stop_data_url { get; set; }
        public string live_racecenter_settings2_race_id { get; set; }
        public string live_racecenter_settings2_live_feed_url { get; set; }
        public string live_racecenter_settings2_live_standings_url { get; set; }
        public string live_racecenter_settings2_live_stage_points_url { get; set; }
        public string live_racecenter_settings2_weekend_feed_url { get; set; }
        public string live_racecenter_settings2_points_url { get; set; }
        public string live_racecenter_settings2_snappytv_feed_url { get; set; }
        public string live_racecenter_settings2_lap_notes_url { get; set; }
        public string live_racecenter_settings2_lap_times_url { get; set; }
        public string live_racecenter_settings2_driver_recap_url { get; set; }
        public string live_racecenter_settings2_lap_averages_url { get; set; }
        public string live_racecenter_settings2_live_flag_data_url { get; set; }
        public string live_racecenter_settings2_pit_stop_data_url { get; set; }
        public string live_racecenter_settings3_race_id { get; set; }
        public string live_racecenter_settings3_live_feed_url { get; set; }
        public string live_racecenter_settings3_live_standings_url { get; set; }
        public string live_racecenter_settings3_live_stage_points_url { get; set; }
        public string live_racecenter_settings3_weekend_feed_url { get; set; }
        public string live_racecenter_settings3_points_url { get; set; }
        public string live_racecenter_settings3_snappytv_feed_url { get; set; }
        public string live_racecenter_settings3_lap_notes_url { get; set; }
        public string live_racecenter_settings3_lap_times_url { get; set; }
        public string live_racecenter_settings3_driver_recap_url { get; set; }
        public string live_racecenter_settings3_lap_averages_url { get; set; }
        public string live_racecenter_settings3_live_flag_data_url { get; set; }
        public string live_racecenter_settings3_pit_stop_data_url { get; set; }
        public string playoff_hub_settings_disable_auto_feed { get; set; }
        public string live_drive__ng_series { get; set; }
        public string live_drive_default_ng_driver_id { get; set; }
        public string live_drive__ng_race_id { get; set; }
        public string live_drive_ng_hide_telemetry { get; set; }
    }
}
