namespace NASCAR_Money.Models
{
    public class ScheduleCombinedFeed
    {
        public int status { get; set; }
        public string message { get; set; }
        public List<Response> response { get; set; }
    }
    public class Response
    {
        public string Race_Name { get; set; }
        public int Race_Id { get; set; }
        public string Race_State { get; set; }
        public string Race_Logo { get; set; }
        public string Race_Logo_Medium { get; set; }
        public string Series_Id { get; set; }
        public string Series_Logo { get; set; }
        public int Track_Id { get; set; }
        public string Track_Name { get; set; }
        public string Alt_Track_Name { get; set; }
        public string Track_Page_URL { get; set; }
        public string Track_Image_URL { get; set; }
        public string Track_Background_Image_URL { get; set; }
        public string Track_Mobile_Image_URL { get; set; }
        public DateTime Race_Date { get; set; }
        public string Race_Date_Plain { get; set; }
        public string Race_Tickets { get; set; }
        public string Race_Tickets_App { get; set; }
        public string Race_Tickets_VA { get; set; }
        public string Race_TV { get; set; }
        public string Race_TV_Display { get; set; }
        public string Race_TV_Logo { get; set; }
        public string Race_TV_Logo_Small { get; set; }
        public string Race_TV_Logo_Small2 { get; set; }
        public string Race_TV_Logo_Dark { get; set; }
        public string Race_Radio { get; set; }
        public string Race_Radio_Logo { get; set; }
        public string Race_Radio_Logo2 { get; set; }
        public string Race_Radio_Logo_Dark { get; set; }
        public string Race_Live_Stream { get; set; }
        public string Race_Live_Stream_Logo { get; set; }
        public string Race_Live_Stream_Logo2 { get; set; }
        public string Race_Live_Stream_Logo_Dark { get; set; }
        public string Race_Additional { get; set; }
        public string Race_Additional_Logo { get; set; }
        public string Race_Additional_Logo2 { get; set; }
        public string Race_Additional_Logo_Dark { get; set; }
        public string Race_Entry_List { get; set; }
        public string Race_Starting_Lineup { get; set; }
        public string Race_URL { get; set; }
        public string Race_Start { get; set; }
        public string Race_End { get; set; }
        public string Race_Result { get; set; }
        public string Driver_Pos1_DriverFirstName { get; set; }
        public string Driver_Pos1_DriverLastName { get; set; }
        public string Driver_Pos2_DriverFirstName { get; set; }
        public string Driver_Pos2_DriverLastName { get; set; }
        public string Driver_Pos3_DriverFirstName { get; set; }
        public string Driver_Pos3_DriverLastName { get; set; }
        public string Driver_Pos1_DriverID { get; set; }
        public string Driver_Pos2_DriverID { get; set; }
        public string Driver_Pos3_DriverID { get; set; }
        public string Driver_Pos1_DriverFiresuit { get; set; }
        public string Driver_Pos2_DriverFiresuit { get; set; }
        public string Driver_Pos3_DriverFiresuit { get; set; }
        public string Driver_Pos1_DriverPageURL { get; set; }
        public string Driver_Pos2_DriverPageURL { get; set; }
        public string Driver_Pos3_DriverPageURL { get; set; }
        public string Race_Recap { get; set; }
        public string News_Hub { get; set; }
        public string Previous_Winner { get; set; }
        public string Previous_Winner_Result_URL { get; set; }
        public string Previous_Winner_Name { get; set; }
        public string Previous_Winner_Headshot { get; set; }
        public string Previous_Winner_Firesuit { get; set; }
        public string Previous_Winner_Badge { get; set; }
        public string Previous_Winner_Page { get; set; }
        public string Current_Winner_DriverID { get; set; }
        public string Current_Winner_Name { get; set; }
        public string Current_Winner_Headshot { get; set; }
        public string Current_Winner_Firesuit { get; set; }
        public string Current_Winner_Badge { get; set; }
        public string Current_Winner_Page { get; set; }
        public string Current_Winner_Car_Number { get; set; }
        public string Playoff_Round { get; set; }
        public string Race_TBD { get; set; }
        public string VIP_Tickets_URL { get; set; }
        public string Lowest_Price { get; set; }
        public string Post_Status { get; set; }
        public string Button_1_Event_Text { get; set; }
        public string Button_1_Event_URL { get; set; }
        public string Button_1_Event_Target { get; set; }
        public string Button_1_Event_Rel { get; set; }
        public string Button_2_Event_Text { get; set; }
        public string Button_2_Event_URL { get; set; }
        public string Button_2_Event_Target { get; set; }
        public string Button_2_Event_Rel { get; set; }
        public string Button_3_Event_Text { get; set; }
        public string Button_3_Event_URL { get; set; }
        public string Button_3_Event_Target { get; set; }
        public string Button_3_Event_Rel { get; set; }
        public object Practice_1_Date { get; set; }
        public string Practice_1_TV { get; set; }
        public string Practice_1_Radio { get; set; }
        public string Practice_1_URL { get; set; }
        public object Practice_2_Date { get; set; }
        public string Practice_2_TV { get; set; }
        public string Practice_2_Radio { get; set; }
        public string Practice_2_URL { get; set; }
        public string Practice_3_Date { get; set; }
        public string Practice_3_TV { get; set; }
        public string Practice_3_Radio { get; set; }
        public string Practice_3_URL { get; set; }
        public object Qualifying_Date { get; set; }
        public string Qualifying_TV { get; set; }
        public string Qualifying_Radio { get; set; }
        public string Qualifying_URL { get; set; }
        public int Actual_Laps { get; set; }
        public double Average_Speed { get; set; }
        public int Race_Season { get; set; }
        public int Scheduled_Laps { get; set; }
        public List<object> Practice { get; set; }
        public List<object> Qualifying { get; set; }
        public DateTime Event_Time_Est { get; set; }
        public string Event_Time_Unix { get; set; }
    }
}
